%% Code generated by libero. DO NOT EDIT.
%%
%% Pre-registers all constructor atoms that may appear in client ETF
%% payloads, so binary_to_term([safe]) can decode them without
%% rejecting unknown atoms.
%%
%% ensure/0 uses persistent_term as a one-shot guard so the
%% binary_to_atom calls only run once per VM lifetime.
%%
%% lists:foreach + fun is used instead of bare binary_to_atom calls
%% because the Erlang compiler optimizes away pure BIF calls whose
%% results are discarded.

-module(server@generated@libero@rpc_atoms).
-export([ensure/0]).

ensure() ->
    case persistent_term:get({?MODULE, done}, false) of
        true -> nil;
        false -> do_ensure()
    end.

do_ensure() ->
    lists:foreach(fun(B) -> binary_to_atom(B) end, [
        <<"app_error">>,
        <<"create">>,
        <<"decode_error">>,
        <<"delete">>,
        <<"error">>,
        <<"false">>,
        <<"internal_error">>,
        <<"load_all">>,
        <<"malformed_request">>,
        <<"nil">>,
        <<"none">>,
        <<"not_found">>,
        <<"ok">>,
        <<"some">>,
        <<"title_required">>,
        <<"todo">>,
        <<"todo_created">>,
        <<"todo_deleted">>,
        <<"todo_params">>,
        <<"todo_toggled">>,
        <<"todos_loaded">>,
        <<"toggle">>,
        <<"true">>,
        <<"unknown_function">>
    ]),
    persistent_term:put({?MODULE, done}, true),
    nil.
