name = "server"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.69.0 and < 1.0.0"
gleam_erlang = "~> 1.0"
gleam_otp = "~> 1.2"
mist = "~> 6.0"
gleam_http = "~> 4.0"
shared = { path = "../shared" }
libero = { path = "../../.." }
